# Dependencies

markdown: kramdown
highlighter: rouge

plugins: 
  - jekyll-seo-tag  

# File rules

exclude:
  - "README.md"
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"  

# Site

title: Ivalice Alliance
keyword: ivalice alliance, community, clan, gaming, final fantasy, xii, xiv
url: https://www.ivalicealliance.net
logo: /assets/images/logo.svg
timezone: America/Los_Angeles
year: 2008
author: 
  name: Balthier

# Data

construct8: https://us-central1-river-octagon-219300.cloudfunctions.net/construct8
discord: https://discord.gg/TEVk6n5
github: ivalicealliance

# Defaults

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true